In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
iris=load_iris()

In [7]:
lr_scores=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)
lr_scores

C:\Users\arnab\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [8]:
np.average(lr_scores)

0.9733333333333333

In [9]:
sv_scores=cross_val_score(SVC(),iris.data,iris.target,cv=3)
sv_scores

array([0.96, 0.98, 0.94])

In [10]:
np.average(sv_scores)

0.96

In [11]:
de_scores=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
de_scores

array([0.98, 0.92, 1.  ])

In [12]:
np.average(de_scores)

0.9666666666666667

In [13]:
rff_scores=cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)
rff_scores

array([0.98, 0.94, 0.98])

In [14]:
np.average(rff_scores)

0.9666666666666667