In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("Homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540437

In [16]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [18]:
112.06244194*3000 +23388.88007794*3 + -3231.71790863*15 + 221323.00186540437

579201.1992897743

In [11]:
reg.predict([[2400,2,5]])

array([520892.03313924])

In [16]:
from joblib import dump,load

In [17]:
dump(reg,'model_joblib')

['model_joblib']

In [18]:
ai=load('model_joblib')

In [21]:
ai.predict([[3000,3,15]])

array([579201.19929613])

In [23]:
ai.predict([[4001,4,12]])

array([724459.73748405])

In [28]:
import pickle

In [29]:
with open('moddl_pickle','wb') as file:
    pickle.dump(reg,file)

In [30]:
with open('moddl_pickle','rb') as file:
    mp=pickle.load(file)

In [32]:
mp.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [34]:
mp.intercept_

221323.00186540437

In [35]:
mp.predict([[3000,3,15]])

array([579201.19929613])